"""Step 2 paired sycophancy feature extraction from syco_dataset.jsonl.

This pipeline uses the paired responses generated by ``run_step2.sh``:

    query + sycophantic response
    query + robust response

For each response, only the first N assistant tokens are scored.  Each token's
residual activation is encoded by the SAE independently, then feature scores
are pooled over tokens in SAE-latent space with top-k mean pooling.
"""

from __future__ import annotations

import argparse
from contextlib import contextmanager, redirect_stderr, redirect_stdout
import json
import logging
import os
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Tuple

import torch

try:
    from tqdm import tqdm
except ModuleNotFoundError:
    class tqdm:  # type: ignore[no-redef]
        def __init__(self, total=0, desc="", unit="", initial=0, **_: Any):
            self.total = total
            self.count = initial
            self.desc = desc
            self.unit = unit

        def __enter__(self):
            if self.desc:
                print(f"{self.desc}: {self.count}/{self.total} {self.unit}".rstrip())
            return self

        def __exit__(self, exc_type, exc, tb):
            return False

        def update(self, n=1):
            self.count += n
            if self.desc:
                print(f"{self.desc}: {self.count}/{self.total} {self.unit}".rstrip())

sys.path.insert(0, os.path.dirname(__file__))

logger = logging.getLogger(__name__)

RESPONSE_TYPES = {"sycophantic", "robust"}
RANKING_METRIC = "mean_delta"
RANKING_ORDER = "descending"


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def setup_file_logger(name: str, log_file: str, level: int = logging.DEBUG) -> logging.Logger:
    ensure_dir(os.path.dirname(log_file))
    log = logging.getLogger(name)
    log.setLevel(level)
    log.handlers.clear()
    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(level)
    file_handler.setFormatter(formatter)
    log.addHandler(file_handler)
    return log


@contextmanager
def redirect_stdio_to_log(log_file: str):
    ensure_dir(os.path.dirname(log_file))
    with open(log_file, "a", encoding="utf-8") as stream:
        with redirect_stdout(stream), redirect_stderr(stream):
            yield


@dataclass(frozen=True)
class ResponsePair:
    pair_id: str
    domain: str
    prompt: str
    sycophantic_response: str
    robust_response: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract paired sycophancy SAE features from syco_dataset.jsonl."
    )
    parser.add_argument("--config", default="configs/step2.yaml")
    parser.add_argument("--model-name", default=None)
    parser.add_argument("--model-path", default=None)
    parser.add_argument("--sae-dir", default=None)
    parser.add_argument("--layer", type=int, default=None)
    parser.add_argument("--dataset-path", default=None)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--log-file", default=None)
    parser.add_argument("--assistant-token-limit", type=int, default=None)
    parser.add_argument("--pool-top-k", type=int, default=None)
    parser.add_argument("--per-pair-top-n", type=int, default=None)
    parser.add_argument("--top-output-k", type=int, default=None)
    parser.add_argument("--checkpoint-interval", type=int, default=None)
    parser.add_argument("--max-pairs", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--dry-run-pairs", type=int, default=5)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--device-map", default=None)
    parser.add_argument("--torch-dtype", default=None, choices=["auto", "float16", "bfloat16", "float32"])
    parser.add_argument("--min-delta", type=float, default=None)
    parser.add_argument("--min-syc-score", type=float, default=None)
    parser.add_argument(
        "--rerank-existing",
        nargs="+",
        default=None,
        metavar="SYCO_FEATURE_DIR",
        help=(
            "Re-rank existing syco_feature outputs without model inference, then exit. "
            "Accepts one or more output directories."
        ),
    )
    parser.add_argument(
        "--no-clamp-negative",
        action="store_true",
        help="Keep negative SAE top-k values instead of clamping them to zero.",
    )
    return parser.parse_args()


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if not value:
        return ""
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    lowered = value.lower()
    if lowered in {"true", "false"}:
        return lowered == "true"
    if lowered in {"null", "none"}:
        return None
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        return value


def load_simple_yaml(path: str) -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    stack: List[Tuple[int, Dict[str, Any]]] = [(-1, data)]
    with open(path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.split("#", 1)[0].rstrip()
            if not line.strip():
                continue
            indent = len(line) - len(line.lstrip(" "))
            key, sep, value = line.strip().partition(":")
            if not sep:
                continue
            key = str(parse_scalar(key))
            while stack and indent <= stack[-1][0]:
                stack.pop()
            parent = stack[-1][1]
            if value.strip():
                parent[key.strip()] = parse_scalar(value)
            else:
                child: Dict[str, Any] = {}
                parent[key.strip()] = child
                stack.append((indent, child))
    return data


def load_config(path: str) -> Dict[str, Any]:
    try:
        import yaml  # type: ignore
    except ModuleNotFoundError:
        return load_simple_yaml(path)
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def resolve_settings(args: argparse.Namespace, cfg: Dict[str, Any]) -> Dict[str, Any]:
    model_cfg = cfg.get("model", {})
    sae_root_cfg = cfg.get("sae", {})
    data_cfg = cfg.get("data", {})
    output_cfg = cfg.get("output", {})
    feature_cfg = cfg.get("feature_extraction", {})

    model_path = args.model_path or model_cfg.get("default_model_path")
    if not model_path and args.model_name:
        model_root = model_cfg.get(
            "model_root",
            "./models",
        )
        model_path = os.path.join(model_root, args.model_name)
    if not model_path:
        raise ValueError("model_path is required via --model-path or config model.default_model_path")

    model_name = args.model_name or os.path.basename(model_path.rstrip("/"))
    sae_cfg = sae_root_cfg.get("configs", {}).get(model_name, {})
    sae_dir = args.sae_dir or sae_cfg.get("sae_dir")
    layer = args.layer if args.layer is not None else sae_cfg.get("layer")
    if not sae_dir or layer is None:
        raise ValueError(f"Missing SAE config for model {model_name}")

    step2_dir = data_cfg.get("step2_dir", output_cfg.get("output_dir", "outputs/step2"))
    dataset_path = (
        args.dataset_path
        or data_cfg.get("dataset_path")
        or os.path.join(step2_dir, model_name, "syco_dataset", "syco_dataset.jsonl")
    )
    output_dir = (
        args.output_dir
        or output_cfg.get("syco_feature_dir")
        or os.path.join(output_cfg.get("output_dir", "outputs/step2"), model_name, "syco_feature")
    )

    log_file = args.log_file or os.path.join("logs", "step2", f"syco_feature_{model_name}.log")

    return {
        "model_name": model_name,
        "model_path": model_path,
        "sae_path": os.path.join(sae_dir, f"layer{layer}.ae.pt"),
        "sae_top_k": int(sae_cfg["top_k"]) if sae_cfg.get("top_k") is not None else None,
        "layer": int(layer),
        "dataset_path": dataset_path,
        "output_dir": output_dir,
        "log_file": log_file,
        "assistant_token_limit": int(
            args.assistant_token_limit
            if args.assistant_token_limit is not None
            else feature_cfg.get("assistant_token_limit", 128)
        ),
        "pool_top_k": int(
            args.pool_top_k
            if args.pool_top_k is not None
            else feature_cfg.get("pool_top_k", 5)
        ),
        "per_pair_top_n": int(
            args.per_pair_top_n
            if args.per_pair_top_n is not None
            else feature_cfg.get("per_pair_top_n", 50)
        ),
        "top_output_k": int(
            args.top_output_k
            if args.top_output_k is not None
            else feature_cfg.get("top_output_k", 200)
        ),
        "checkpoint_interval": int(
            args.checkpoint_interval
            if args.checkpoint_interval is not None
            else feature_cfg.get("checkpoint_interval", 25)
        ),
        "device_map": args.device_map or model_cfg.get("device_map", "auto"),
        "torch_dtype": args.torch_dtype or model_cfg.get("torch_dtype", "bfloat16"),
        "min_delta": float(
            args.min_delta
            if args.min_delta is not None
            else feature_cfg.get("min_delta", 0.0)
        ),
        "min_syc_score": float(
            args.min_syc_score
            if args.min_syc_score is not None
            else feature_cfg.get("min_syc_score", 0.0)
        ),
        "clamp_negative": not args.no_clamp_negative,
    }


def read_jsonl(path: str) -> Iterable[Dict[str, Any]]:
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on {path}:{line_no}: {exc}") from exc


def load_response_pairs(path: str) -> List[ResponsePair]:
    grouped: Dict[Tuple[str, str], Dict[str, Any]] = {}
    order: List[Tuple[str, str]] = []

    for rec in read_jsonl(path):
        required = {"id", "domain", "prompt", "response", "response_type"}
        missing = required - set(rec.keys())
        if missing:
            raise ValueError(f"Missing fields {sorted(missing)} in record id={rec.get('id')}")
        response_type = str(rec["response_type"]).strip()
        if response_type not in RESPONSE_TYPES:
            raise ValueError(f"Unsupported response_type={response_type!r} for id={rec.get('id')}")

        key = (str(rec["id"]).strip(), str(rec["prompt"]).strip())
        if key not in grouped:
            grouped[key] = {
                "id": key[0],
                "prompt": key[1],
                "domain": str(rec["domain"]).strip(),
                "responses": {},
            }
            order.append(key)

        group = grouped[key]
        if group["domain"] != str(rec["domain"]).strip():
            raise ValueError(f"Domain mismatch for id={key[0]}")
        if response_type in group["responses"]:
            raise ValueError(f"Duplicate response_type={response_type} for id={key[0]}")
        group["responses"][response_type] = str(rec["response"]).strip()

    pairs: List[ResponsePair] = []
    for key in order:
        group = grouped[key]
        responses = group["responses"]
        if set(responses) != RESPONSE_TYPES:
            raise ValueError(f"Incomplete pair for id={group['id']}: got {sorted(responses)}")
        pairs.append(
            ResponsePair(
                pair_id=group["id"],
                domain=group["domain"],
                prompt=group["prompt"],
                sycophantic_response=responses["sycophantic"],
                robust_response=responses["robust"],
            )
        )
    return pairs


def torch_dtype_from_name(name: str) -> torch.dtype | str:
    if name == "auto":
        return "auto"
    if name == "float16":
        return torch.float16
    if name == "bfloat16":
        return torch.bfloat16
    if name == "float32":
        return torch.float32
    raise ValueError(f"Unsupported torch dtype: {name}")


def load_model_and_tokenizer(model_path: str, device_map: str, torch_dtype: str):
    from transformers import AutoModelForCausalLM, AutoTokenizer

    logger.info("Loading tokenizer from %s", model_path)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    logger.info("Loading model from %s", model_path)
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch_dtype_from_name(torch_dtype),
        device_map=device_map,
        trust_remote_code=True,
    )
    model.eval()
    logger.info(
        "Model loaded: layers=%s hidden_size=%s",
        model.config.num_hidden_layers,
        model.config.hidden_size,
    )
    return model, tokenizer


def load_sae_cpu(sae_path: str, configured_top_k: int | None = None) -> Dict[str, Any]:
    logger.info("Loading SAE from %s", sae_path)
    state = torch.load(sae_path, map_location="cpu", weights_only=False)

    if "encoder.weight" in state and "encoder.bias" in state:
        enc_w = state["encoder.weight"].float()
        enc_b = state["encoder.bias"].float()
    elif "W_enc" in state and "b_enc" in state:
        enc_w = state["W_enc"].float()
        enc_b = state["b_enc"].float()
    else:
        raise KeyError(
            "Unsupported SAE checkpoint schema: expected encoder.weight/encoder.bias "
            "or W_enc/b_enc"
        )

    checkpoint_k = state.get("k")
    if checkpoint_k is not None:
        sae_k = int(checkpoint_k.item() if isinstance(checkpoint_k, torch.Tensor) else checkpoint_k)
        if configured_top_k is not None and sae_k != configured_top_k:
            raise ValueError(
                f"Configured SAE top_k={configured_top_k} does not match checkpoint k={sae_k}"
            )
    elif configured_top_k is not None:
        sae_k = int(configured_top_k)
    else:
        raise KeyError("SAE checkpoint does not contain k; configure sae.configs.<model>.top_k")

    n_features, d_model = enc_w.shape
    if enc_b.shape != (n_features,):
        raise ValueError(
            f"SAE encoder bias shape={tuple(enc_b.shape)} does not match n_features={n_features}"
        )
    logger.info("SAE loaded: n_features=%s d_model=%s sae_top_k=%s", n_features, d_model, sae_k)
    return {
        "encoder_weight_cpu": enc_w,
        "encoder_bias_cpu": enc_b,
        "sae_top_k": sae_k,
        "n_features": n_features,
        "d_model": d_model,
        "device_cache": {},
    }


def sae_tensors_for_device(sae: Dict[str, Any], device: torch.device) -> Tuple[torch.Tensor, torch.Tensor]:
    key = str(device)
    cached = sae["device_cache"].get(key)
    if cached is None:
        logger.info("Moving SAE encoder to %s", device)
        cached = (
            sae["encoder_weight_cpu"].to(device=device, dtype=torch.float32),
            sae["encoder_bias_cpu"].to(device=device, dtype=torch.float32),
        )
        sae["device_cache"][key] = cached
    return cached


class LayerHook:
    def __init__(self, model: Any, layer_idx: int):
        self.hidden_states: torch.Tensor | None = None
        self._handle = model.model.layers[layer_idx].register_forward_hook(self._hook)

    def _hook(self, module: Any, inputs: Tuple[Any, ...], output: Any) -> None:
        hs = output[0] if isinstance(output, tuple) else output
        if hs.dim() == 3:
            hs = hs.squeeze(0)
        self.hidden_states = hs.detach()

    def remove(self) -> None:
        self._handle.remove()


def encode_prompt_response(
    tokenizer: Any,
    prompt: str,
    response: str,
    assistant_token_limit: int,
) -> Tuple[torch.Tensor, int]:
    messages = [{"role": "user", "content": prompt}]
    try:
        prefix = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )
    except TypeError:
        prefix = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

    prefix_ids = tokenizer(prefix, add_special_tokens=False)["input_ids"]
    response_ids = tokenizer(response, add_special_tokens=False)["input_ids"][:assistant_token_limit]
    if not response_ids:
        raise ValueError("Empty response after tokenization")
    input_ids = torch.tensor([prefix_ids + response_ids], dtype=torch.long)
    return input_ids, len(response_ids)


def feature_scores_for_response(
    model: Any,
    tokenizer: Any,
    hook: LayerHook,
    sae: Dict[str, Any],
    prompt: str,
    response: str,
    layer_idx: int,
    assistant_token_limit: int,
    pool_top_k: int,
    clamp_negative: bool,
) -> torch.Tensor:
    input_ids, response_len = encode_prompt_response(
        tokenizer,
        prompt,
        response,
        assistant_token_limit,
    )
    input_device = next(model.parameters()).device
    input_ids = input_ids.to(input_device)
    attention_mask = torch.ones_like(input_ids, device=input_device)

    hook.hidden_states = None
    with torch.no_grad():
        model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)

    if hook.hidden_states is None:
        raise RuntimeError(f"No hidden states captured for layer {layer_idx}")

    hidden = hook.hidden_states[-response_len:].float()
    enc_w, enc_b = sae_tensors_for_device(sae, hidden.device)
    sae_top_k = min(int(sae["sae_top_k"]), int(sae["n_features"]))
    pool_k = min(pool_top_k, hidden.shape[0])

    with torch.no_grad():
        z = hidden @ enc_w.T + enc_b
        top_vals, top_idx = torch.topk(z, sae_top_k, dim=-1)
        if clamp_negative:
            top_vals = top_vals.clamp_min(0)
        sparse = torch.zeros_like(z)
        sparse.scatter_(1, top_idx, top_vals)
        pooled = torch.topk(sparse, pool_k, dim=0).values.mean(dim=0)
    return pooled.detach().cpu()


def init_stats(n_features: int) -> Dict[str, Any]:
    return {
        "processed_pairs": 0,
        "processed_ids": [],
        "pair_top_delta_count": torch.zeros(n_features, dtype=torch.long),
        "positive_delta_count": torch.zeros(n_features, dtype=torch.long),
        "delta_sum": torch.zeros(n_features, dtype=torch.float64),
        "positive_delta_sum": torch.zeros(n_features, dtype=torch.float64),
        "syc_score_sum": torch.zeros(n_features, dtype=torch.float64),
        "robust_score_sum": torch.zeros(n_features, dtype=torch.float64),
        "domain_pair_counts": Counter(),
        "domain_top_delta_counts": defaultdict(Counter),
    }


def save_checkpoint(path: str, stats: Dict[str, Any], settings: Dict[str, Any]) -> None:
    ensure_dir(os.path.dirname(path))
    torch.save(
        {
            "settings": settings,
            "processed_pairs": stats["processed_pairs"],
            "processed_ids": stats["processed_ids"],
            "pair_top_delta_count": stats["pair_top_delta_count"],
            "positive_delta_count": stats["positive_delta_count"],
            "delta_sum": stats["delta_sum"],
            "positive_delta_sum": stats["positive_delta_sum"],
            "syc_score_sum": stats["syc_score_sum"],
            "robust_score_sum": stats["robust_score_sum"],
            "domain_pair_counts": dict(stats["domain_pair_counts"]),
            "domain_top_delta_counts": {
                domain: dict(counter)
                for domain, counter in stats["domain_top_delta_counts"].items()
            },
        },
        path,
    )


def load_checkpoint(path: str, n_features: int) -> Dict[str, Any] | None:
    if not os.path.exists(path):
        return None
    ckpt = torch.load(path, map_location="cpu", weights_only=False)
    stats = init_stats(n_features)
    for key in (
        "processed_pairs",
        "processed_ids",
        "pair_top_delta_count",
        "positive_delta_count",
        "delta_sum",
        "positive_delta_sum",
        "syc_score_sum",
        "robust_score_sum",
    ):
        stats[key] = ckpt[key]
    stats["domain_pair_counts"] = Counter(ckpt.get("domain_pair_counts", {}))
    stats["domain_top_delta_counts"] = defaultdict(Counter)
    for domain, counter in ckpt.get("domain_top_delta_counts", {}).items():
        stats["domain_top_delta_counts"][domain] = Counter(counter)
    return stats


def update_stats(
    stats: Dict[str, Any],
    pair: ResponsePair,
    syc_scores: torch.Tensor,
    robust_scores: torch.Tensor,
    per_pair_top_n: int,
    min_delta: float,
    min_syc_score: float,
) -> None:
    delta = syc_scores.double() - robust_scores.double()
    syc_double = syc_scores.double()
    robust_double = robust_scores.double()
    positive_mask = (delta > min_delta) & (syc_double > min_syc_score)

    stats["delta_sum"] += delta
    stats["positive_delta_sum"] += torch.where(delta > 0, delta, torch.zeros_like(delta))
    stats["syc_score_sum"] += syc_double
    stats["robust_score_sum"] += robust_double
    stats["positive_delta_count"] += positive_mask.long()

    candidate_delta = torch.where(positive_mask, delta, torch.full_like(delta, float("-inf")))
    finite_count = int(torch.isfinite(candidate_delta).sum().item())
    if finite_count:
        k = min(per_pair_top_n, finite_count)
        _, top_idx = torch.topk(candidate_delta, k)
        stats["pair_top_delta_count"][top_idx] += 1
        for fid in top_idx.tolist():
            stats["domain_top_delta_counts"][pair.domain][fid] += 1

    stats["domain_pair_counts"][pair.domain] += 1
    stats["processed_pairs"] += 1
    stats["processed_ids"].append(pair.pair_id)


def ranked_features(stats: Dict[str, Any], total_pairs: int) -> List[Dict[str, Any]]:
    pair_top = stats["pair_top_delta_count"]
    positive_count = stats["positive_delta_count"]
    candidate = torch.nonzero((pair_top > 0) | (positive_count > 0), as_tuple=False).flatten()
    if candidate.numel() == 0:
        return []

    mean_delta = stats["delta_sum"] / max(total_pairs, 1)
    mean_positive_delta = stats["positive_delta_sum"] / max(total_pairs, 1)
    mean_syc = stats["syc_score_sum"] / max(total_pairs, 1)
    mean_robust = stats["robust_score_sum"] / max(total_pairs, 1)

    rows: List[Dict[str, Any]] = []
    domain_top_delta_counts = stats["domain_top_delta_counts"]
    for fid in candidate.tolist():
        domain_counts = {
            domain: int(counter.get(fid, 0))
            for domain, counter in sorted(domain_top_delta_counts.items())
            if counter.get(fid, 0)
        }
        rows.append(
            {
                "feature_id": int(fid),
                "pair_top_delta_count": int(pair_top[fid].item()),
                "pair_top_delta_rate": float(pair_top[fid].item() / max(total_pairs, 1)),
                "positive_delta_count": int(positive_count[fid].item()),
                "positive_delta_rate": float(positive_count[fid].item() / max(total_pairs, 1)),
                "mean_delta": float(mean_delta[fid].item()),
                "mean_positive_delta": float(mean_positive_delta[fid].item()),
                "mean_syc_score": float(mean_syc[fid].item()),
                "mean_robust_score": float(mean_robust[fid].item()),
                "domain_top_delta_counts": domain_counts,
            }
        )

    return rank_feature_rows(rows)


def rank_feature_rows(rows: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    ranked = [dict(row) for row in rows]
    ranked.sort(key=lambda row: float(row[RANKING_METRIC]), reverse=True)
    for rank, row in enumerate(ranked, 1):
        row["rank"] = rank
    return ranked


def summary_markdown(summary: Dict[str, Any], top_features: List[Dict[str, Any]]) -> str:
    md_lines = [
        "# Step 2 Syco Feature Summary",
        "",
        f"**Model**: `{summary['model_name']}`  ",
        f"**Layer**: `{summary['layer']}`  ",
        f"**Dataset**: `{summary['dataset_path']}`  ",
        f"**Processed pairs**: `{summary['processed_pairs']}`  ",
        f"**Assistant token limit**: `{summary['assistant_token_limit']}`  ",
        f"**SAE latent pooling**: `top-{summary['pool_top_k']} mean`  ",
        f"**Per-pair candidate frequency**: `top-{summary['per_pair_top_n']} positive deltas`  ",
        "**Ranking**: `Mean Delta (descending)`  ",
        "",
        "## Top Features",
        "",
        "| Rank | Feature ID | Pair Top Count | Pair Top Rate | Positive Delta Count | Mean Delta | Mean Syco Score | Mean Robust Score |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in top_features[:50]:
        md_lines.append(
            f"| {row['rank']} | {row['feature_id']} | "
            f"{row['pair_top_delta_count']} | {row['pair_top_delta_rate']:.4f} | "
            f"{row['positive_delta_count']} | {row['mean_delta']:.6f} | "
            f"{row['mean_syc_score']:.6f} | {row['mean_robust_score']:.6f} |"
        )
    return "\n".join(md_lines) + "\n"


def rerank_existing_outputs(output_dir: str) -> Dict[str, Any]:
    required = ("features.jsonl", "top_features.json", "summary.json", "summary.md")
    missing = [name for name in required if not os.path.isfile(os.path.join(output_dir, name))]
    if missing:
        raise FileNotFoundError(f"Missing existing output(s) in {output_dir}: {missing}")

    features = rank_feature_rows(read_jsonl(os.path.join(output_dir, "features.jsonl")))
    with open(os.path.join(output_dir, "summary.json"), "r", encoding="utf-8") as f:
        summary = json.load(f)
    top_output_k = int(summary.get("top_output_k", 200))
    top_features = features[:top_output_k]
    summary["ranking_metric"] = RANKING_METRIC
    summary["ranking_order"] = RANKING_ORDER
    summary["top_feature_ids"] = [row["feature_id"] for row in top_features]

    replacements = {
        "features.jsonl": lambda path: write_jsonl(path, features),
        "top_features.json": lambda path: write_json(path, top_features),
        "summary.json": lambda path: write_json(path, summary),
    }
    for name, writer in replacements.items():
        temp_path = os.path.join(output_dir, f".{name}.rerank.tmp")
        writer(temp_path)
        os.replace(temp_path, os.path.join(output_dir, name))

    markdown_temp = os.path.join(output_dir, ".summary.md.rerank.tmp")
    with open(markdown_temp, "w", encoding="utf-8") as f:
        f.write(summary_markdown(summary, top_features))
    os.replace(markdown_temp, os.path.join(output_dir, "summary.md"))

    stats_path = os.path.join(output_dir, "feature_stats.pt")
    if os.path.isfile(stats_path):
        payload = torch.load(stats_path, map_location="cpu", weights_only=False)
        if isinstance(payload, dict):
            payload["summary"] = summary
            stats_temp = os.path.join(output_dir, ".feature_stats.pt.rerank.tmp")
            torch.save(payload, stats_temp)
            os.replace(stats_temp, stats_path)
    return top_features[0]


def write_json(path: str, data: Any) -> None:
    ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def write_jsonl(path: str, rows: Iterable[Dict[str, Any]]) -> None:
    ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_outputs(
    output_dir: str,
    settings: Dict[str, Any],
    stats: Dict[str, Any],
    pairs: List[ResponsePair],
    top_output_k: int,
) -> None:
    ensure_dir(output_dir)
    total_pairs = stats["processed_pairs"]
    features = ranked_features(stats, total_pairs)
    top_features = features[:top_output_k]

    summary = {
        "model_name": settings["model_name"],
        "model_path": settings["model_path"],
        "sae_path": settings["sae_path"],
        "layer": settings["layer"],
        "dataset_path": settings["dataset_path"],
        "assistant_token_limit": settings["assistant_token_limit"],
        "pool_top_k": settings["pool_top_k"],
        "per_pair_top_n": settings["per_pair_top_n"],
        "min_delta": settings["min_delta"],
        "min_syc_score": settings["min_syc_score"],
        "clamp_negative": settings["clamp_negative"],
        "total_pairs_available": len(pairs),
        "processed_pairs": total_pairs,
        "domain_pair_counts": dict(stats["domain_pair_counts"]),
        "candidate_feature_count": len(features),
        "top_output_k": top_output_k,
        "ranking_metric": RANKING_METRIC,
        "ranking_order": RANKING_ORDER,
        "top_feature_ids": [row["feature_id"] for row in top_features],
    }

    write_jsonl(os.path.join(output_dir, "features.jsonl"), features)
    write_json(os.path.join(output_dir, "top_features.json"), top_features)
    write_json(os.path.join(output_dir, "summary.json"), summary)
    torch.save(
        {
            "settings": settings,
            "summary": summary,
            "pair_top_delta_count": stats["pair_top_delta_count"],
            "positive_delta_count": stats["positive_delta_count"],
            "delta_sum": stats["delta_sum"],
            "positive_delta_sum": stats["positive_delta_sum"],
            "syc_score_sum": stats["syc_score_sum"],
            "robust_score_sum": stats["robust_score_sum"],
        },
        os.path.join(output_dir, "feature_stats.pt"),
    )

    with open(os.path.join(output_dir, "summary.md"), "w", encoding="utf-8") as f:
        f.write(summary_markdown(summary, top_features))

    logger.info("Wrote syco feature outputs to %s", output_dir)
    logger.info("Top feature ids: %s", summary["top_feature_ids"][:20])


def cleanup_output(output_dir: str) -> None:
    if not os.path.isdir(output_dir):
        return
    for name in (
        "checkpoint.pt",
        "feature_stats.pt",
        "features.jsonl",
        "top_features.json",
        "summary.json",
        "summary.md",
    ):
        path = os.path.join(output_dir, name)
        if os.path.exists(path):
            os.remove(path)


def main() -> None:
    args = parse_args()
    if args.rerank_existing:
        for output_dir in args.rerank_existing:
            top_feature = rerank_existing_outputs(output_dir)
            print(
                f"[reranked] {output_dir}: top feature f{top_feature['feature_id']} "
                f"(mean_delta={top_feature['mean_delta']:.9f})"
            )
        return
    cfg = load_config(args.config)
    settings = resolve_settings(args, cfg)

    setup_file_logger("step2_syco_feature", settings["log_file"])
    setup_file_logger(__name__, settings["log_file"])

    logger.info("=" * 80)
    logger.info("Step 2 paired syco feature extraction")
    for key in sorted(settings):
        logger.info("%s: %s", key, settings[key])

    pairs = load_response_pairs(settings["dataset_path"])
    if args.max_pairs is not None:
        pairs = pairs[: args.max_pairs]
    if args.dry_run:
        pairs = pairs[: args.dry_run_pairs]
    logger.info("Loaded %s paired records", len(pairs))
    logger.info("Domain counts: %s", dict(Counter(pair.domain for pair in pairs)))

    if args.validate_only:
        logger.info("Validation only complete")
        return

    if args.overwrite:
        cleanup_output(settings["output_dir"])

    with redirect_stdio_to_log(settings["log_file"]):
        model, tokenizer = load_model_and_tokenizer(
            settings["model_path"],
            settings["device_map"],
            settings["torch_dtype"],
        )
        sae = load_sae_cpu(settings["sae_path"], settings["sae_top_k"])

    if model.config.hidden_size != sae["d_model"]:
        raise ValueError(
            f"Model hidden_size={model.config.hidden_size} does not match SAE d_model={sae['d_model']}"
        )

    checkpoint_path = os.path.join(settings["output_dir"], "checkpoint.pt")
    stats = load_checkpoint(checkpoint_path, sae["n_features"])
    if stats is None:
        stats = init_stats(sae["n_features"])
    else:
        logger.info("Resumed checkpoint with %s processed pairs", stats["processed_pairs"])

    processed = set(stats["processed_ids"])
    pending_pairs = [pair for pair in pairs if pair.pair_id not in processed]
    logger.info("Pending pairs: %s", len(pending_pairs))

    hook = LayerHook(model, settings["layer"])
    try:
        with tqdm(
            total=len(pending_pairs),
            desc="Scoring pairs",
            unit="pair",
            file=sys.stdout,
            dynamic_ncols=True,
        ) as pbar:
            for pair in pending_pairs:
                with redirect_stdio_to_log(settings["log_file"]):
                    syc_scores = feature_scores_for_response(
                        model=model,
                        tokenizer=tokenizer,
                        hook=hook,
                        sae=sae,
                        prompt=pair.prompt,
                        response=pair.sycophantic_response,
                        layer_idx=settings["layer"],
                        assistant_token_limit=settings["assistant_token_limit"],
                        pool_top_k=settings["pool_top_k"],
                        clamp_negative=settings["clamp_negative"],
                    )
                    robust_scores = feature_scores_for_response(
                        model=model,
                        tokenizer=tokenizer,
                        hook=hook,
                        sae=sae,
                        prompt=pair.prompt,
                        response=pair.robust_response,
                        layer_idx=settings["layer"],
                        assistant_token_limit=settings["assistant_token_limit"],
                        pool_top_k=settings["pool_top_k"],
                        clamp_negative=settings["clamp_negative"],
                    )
                update_stats(
                    stats=stats,
                    pair=pair,
                    syc_scores=syc_scores,
                    robust_scores=robust_scores,
                    per_pair_top_n=settings["per_pair_top_n"],
                    min_delta=settings["min_delta"],
                    min_syc_score=settings["min_syc_score"],
                )

                if stats["processed_pairs"] % settings["checkpoint_interval"] == 0:
                    save_checkpoint(checkpoint_path, stats, settings)
                    logger.info("Checkpoint saved at %s pairs", stats["processed_pairs"])
                pbar.update(1)
    finally:
        hook.remove()

    save_checkpoint(checkpoint_path, stats, settings)
    write_outputs(
        output_dir=settings["output_dir"],
        settings=settings,
        stats=stats,
        pairs=pairs,
        top_output_k=settings["top_output_k"],
    )


if __name__ == "__main__":
    main()
